packages:
  - apps/*
  - packages/*
  - infra/*

overrides:
  braces@<2.3.1: '>=2.3.1'
  yargs-parser@<=5.0.0: '>=5.0.1'
  braces@<3.0.3: '>=3.0.3'
  micromatch@<4.0.8: '>=4.0.8'
  http-proxy-middleware@<2.0.7: '>=2.0.7'
  esbuild@<=0.24.2: '>=0.25.0'
